### ISSUE TITLE
aGVsbG8gYmVuIHJlZWY=

### ISSUE THREAD

**Issue by serifonium** [aeolus-1/fortnite3#1]
aGVsbG8gYmVuIHJlZWYsIGl0IGhhcyBiZWVuIGEgd2hpbGUgc2luY2Ugd2UgbGFzdCBzcG9rZS4gR28gdG8gdGhlc2UgY29vcmRpbmF0ZXM6Ci0yNy40MTU0MzIgCjE1Mi45ODgxNDcKYXQgMTQ6MDAsIDI1IHNlcCwgYSBwcml6ZSBpcyB3YWl0aW5nLg==

**Comment by aeolus-1** [comment]
yes
